name: libvips_ffi_desktop
description: Meta package for libvips_ffi desktop support (macOS, Windows, Linux).
version: 0.1.0+8.16.0
homepage: https://github.com/fluttercandies/libvips_ffi
repository: https://github.com/fluttercandies/libvips_ffi
issue_tracker: https://github.com/fluttercandies/libvips_ffi/issues
documentation: https://fluttercandies.github.io/libvips_ffi/

topics:
  - image
  - image-processing
  - ffi
  - libvips
  - desktop

environment:
  sdk: ^3.5.0
  flutter: '>=3.10.0'

dependencies:
  libvips_ffi_core: ^0.1.0+8.16.0
  libvips_ffi_macos: ^0.1.0+8.17.0
  libvips_ffi_windows: ^0.1.0+8.17.3
  libvips_ffi_linux: ^0.1.0+8.16.0
