name: libvips_ffi_windows
description: Pre-compiled libvips for Windows. Part of the libvips_ffi package family.
version: 0.1.0+8.17.3
homepage: https://github.com/fluttercandies/libvips_ffi
repository: https://github.com/fluttercandies/libvips_ffi
issue_tracker: https://github.com/fluttercandies/libvips_ffi/issues
documentation: https://fluttercandies.github.io/libvips_ffi/

topics:
  - image
  - image-processing
  - ffi
  - libvips
  - windows

environment:
  sdk: ^3.5.0
  flutter: '>=3.10.0'

dependencies:
  ffi: ^2.1.0
  libvips_ffi_core: ^0.1.0+8.16.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: LibvipsFfiWindowsPluginCApi
        ffiPlugin: true
