name: libvips_flutter_example_base
description: Base UI components for libvips_ffi Flutter example apps.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  libvips_ffi: ^0.1.0
  path_provider: ^2.1.0
  image_picker: ^1.0.0

flutter:
  uses-material-design: true
