name: libvips_ffi_loader
description: Dynamic library loader for libvips_ffi with callback-based download support.
version: 0.1.0+8.16.0
homepage: https://github.com/fluttercandies/libvips_ffi
repository: https://github.com/fluttercandies/libvips_ffi
issue_tracker: https://github.com/fluttercandies/libvips_ffi/issues
documentation: https://fluttercandies.github.io/libvips_ffi/

topics:
  - image
  - image-processing
  - ffi
  - libvips
  - dynamic-loading

environment:
  sdk: ^3.5.0

dependencies:
  libvips_ffi_core: ^0.1.0+8.16.0
  path: ^1.9.0
