name: libvips_ffi_loader
description: Dynamic library loader for libvips_ffi with callback-based download support.
version: 0.1.0
homepage: https://github.com/CaiJingLong/libvips_ffi
repository: https://github.com/CaiJingLong/libvips_ffi
issue_tracker: https://github.com/CaiJingLong/libvips_ffi/issues

topics:
  - image
  - image-processing
  - ffi
  - libvips
  - dynamic-loading

environment:
  sdk: ^3.5.0

dependencies:
  libvips_ffi_core:
    path: ../libvips_ffi_core
  path: ^1.9.0
