name: libvips_ffi_macos
description: Pre-compiled libvips for macOS. Part of the libvips_ffi package family.
version: 0.1.0+8.17.0
homepage: https://github.com/CaiJingLong/libvips_ffi
repository: https://github.com/CaiJingLong/libvips_ffi
issue_tracker: https://github.com/CaiJingLong/libvips_ffi/issues

topics:
  - image
  - image-processing
  - ffi
  - libvips
  - macos

environment:
  sdk: ^3.5.0
  flutter: '>=3.10.0'

dependencies:
  libvips_ffi_core: ^0.1.0+8.16.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: LibvipsFfiMacosPlugin
        ffiPlugin: true
